apiVersion: "zeroci.io/v1"
kind: Build
metadata:
  name: build-2
status: peinding
environment:
  GIT_COMMIT: "$(git rev-parse --short HEAD)"
pipeline:
- type: env
  GIT_COMMIT:
    command: "git rev-parse --short HEAD"
- type: env
  DOCKER_REPO: aidbox/listner
- type: bash
  dir: example
  command: docker build -t $DOCKER_REPO:v_$GIT_COMMIT .
- type: bash
  dir: example
  command: docker tag $DOCKER_REPO:v_$GIT_COMMIT $DOCKER_REPO:latest

- type: bash
  command: docker login -p $DOCKER_PASSWORD -u $DOCKER_USER

- type: bash
  command: docker push $DOCKER_REPO:v_$GIT_COMMIT
- type: bash
  command: docker push $DOCKER_REPO:latest
# - type: bash
#   dir: example
#   command: helm upgrade --set image.tag=v_$GIT_COMMIT,image.repository=$DOCKER_REPO -i aidbox-next charts/aidbox-example
